---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    name: pgadmin-service
    app: pgadmin
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
