---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  labels:
    name: pgadmin-pvc
    app: pgadmin
spec:
  storageClassName: nfs
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: "100Mi"
  selector:
    matchLabels:
      name: pgadmin-pv