---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: devops
  labels:
    name: pgadmin
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      namespace: devops
      labels:
        app: pgadmin
    spec:      
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        envFrom:
          - configMapRef:
              name: pgadmin-configmap
        ports:
        - name: pgadmin-port
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: pgadmin-storage
          mountPath: /var/lib/pgadmin
      volumes:
      - name: pgadmin-storage
        persistentVolumeClaim:
          claimName: pgadmin-pvc