# Change password on first connexion
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-configmap
  labels:
    name: pgadmin-configmap
    app: pgadmin
data:
  PGADMIN_DEFAULT_EMAIL: pedsf.fullstack@gmail.com
  PGADMIN_DEFAULT_PASSWORD: pgadmin
