---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: devops
  labels:
    name: pgadmin-service
    app: pgadmin
spec:
  type: LoadBalancer
  selector:
    app: pgadmin
  ports:
  - port: 80
    protocol: TCP
